name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
         
      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1

      - name: Run Build
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build //...

      - name: Run Test
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel --test_output=errors" test //...
