name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Bazel Cache
        id: bazel-cache
        uses: actions/cache@v2
        env:
          version: 4.2.1
        with:
          path: | 
            ~/.cache/bazel
          key: ${{ runner.os }}-{{ env.version }}-bazel-cache
      
      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1

      - name: Run Build
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build //...

      - name: Run Test
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" test //...
